USE `lsrp`;

ALTER TABLE `player_characters`
    ADD COLUMN IF NOT EXISTS `character_created` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `name`,
    ADD COLUMN IF NOT EXISTS `gender` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `character_created`,
    ADD COLUMN IF NOT EXISTS `birth_day` TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER `gender`,
    ADD COLUMN IF NOT EXISTS `birth_month` TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER `birth_day`,
    ADD COLUMN IF NOT EXISTS `birth_year` SMALLINT UNSIGNED NOT NULL DEFAULT 2000 AFTER `birth_month`,
    ADD COLUMN IF NOT EXISTS `skin_tone` TINYINT UNSIGNED NOT NULL DEFAULT 2 AFTER `birth_year`,
    ADD COLUMN IF NOT EXISTS `voice` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `skin_tone`,
    ADD COLUMN IF NOT EXISTS `height_cm` SMALLINT UNSIGNED NOT NULL DEFAULT 175 AFTER `voice`,
    ADD COLUMN IF NOT EXISTS `weight_kg` SMALLINT UNSIGNED NOT NULL DEFAULT 70 AFTER `height_cm`,
    ADD COLUMN IF NOT EXISTS `birth_place` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `weight_kg`;